# config/models.yaml
default_model: llama3.2:latest

models:
  mistral:latest:
    provider: ollama
    model_name: mistral:latest
    family: mistral
    variant: null
    params:
      context_length: 8192
      temperature: 0.7
      top_p: 0.9
      repeat_penalty: 1.1
      top_k: 50
      presence_penalty: 0
      frequency_penalty: 0
  gemma2:latest:
    provider: ollama
    model_name: gemma2:latest
    family: gemma
    variant: null
    params:
      context_length: 8192
      temperature: 0.7
      top_p: 0.9
      repeat_penalty: 1.1
      top_k: 40
      presence_penalty: 0
      frequency_penalty: 0
  llama3.2:latest:
    provider: ollama
    model_name: llama3.2:latest
    family: llama
    variant: null
    params:
      context_length: 4096
      temperature: 0.7
      top_p: 0.9
      repeat_penalty: 1.1
      top_k: 40
      presence_penalty: 0
      frequency_penalty: 0
